/*
 * KeyCode.cpp
 *
 *  Created on: 29.12.2019
 *      Author: florian
 */

#include "KeyCode.h"

namespace Zoe {

std::map<std::string, unsigned int> keyMap;

#define MAP(KEY) keyMap[#KEY] = KEY;

void initKeyMap() {
	MAP(KEY_SPACE);
	MAP(KEY_APOSTROPHE);
	MAP(KEY_COMMA);
	MAP(KEY_MINUS);
	MAP(KEY_PERIOD);
	MAP(KEY_SLASH);
	MAP(KEY_0);
	MAP(KEY_1);
	MAP(KEY_2);
	MAP(KEY_3);
	MAP(KEY_4);
	MAP(KEY_5);
	MAP(KEY_6);
	MAP(KEY_7);
	MAP(KEY_8);
	MAP(KEY_9);
	MAP(KEY_SEMICOLON);
	MAP(KEY_EQUAL);
	MAP(KEY_A);
	MAP(KEY_B);
	MAP(KEY_C);
	MAP(KEY_D);
	MAP(KEY_E);
	MAP(KEY_F);
	MAP(KEY_G);
	MAP(KEY_H);
	MAP(KEY_I);
	MAP(KEY_J);
	MAP(KEY_K);
	MAP(KEY_L);
	MAP(KEY_M);
	MAP(KEY_N);
	MAP(KEY_O);
	MAP(KEY_P);
	MAP(KEY_Q);
	MAP(KEY_R);
	MAP(KEY_S);
	MAP(KEY_T);
	MAP(KEY_U);
	MAP(KEY_V);
	MAP(KEY_W);
	MAP(KEY_X);
	MAP(KEY_Y);
	MAP(KEY_Z);
	MAP(KEY_LEFT_BRACKET);
	MAP(KEY_BACKSLASH);
	MAP(KEY_RIGHT_BRACKET);
	MAP(KEY_GRAVE_ACCENT);
	MAP(KEY_WORLD_1);
	MAP(KEY_WORLD_2);
	MAP(KEY_ESCAPE);
	MAP(KEY_ENTER);
	MAP(KEY_TAB);
	MAP(KEY_BACKSPACE);
	MAP(KEY_INSERT);
	MAP(KEY_DELETE);
	MAP(KEY_RIGHT);
	MAP(KEY_LEFT);
	MAP(KEY_DOWN);
	MAP(KEY_UP);
	MAP(KEY_PAGE_UP);
	MAP(KEY_PAGE_DOWN);
	MAP(KEY_HOME);
	MAP(KEY_END);
	MAP(KEY_CAPS_LOCK);
	MAP(KEY_SCROLL_LOCK);
	MAP(KEY_NUM_LOCK);
	MAP(KEY_PRINT_SCREEN);
	MAP(KEY_PAUSE);
	MAP(KEY_F1);
	MAP(KEY_F2);
	MAP(KEY_F3);
	MAP(KEY_F4);
	MAP(KEY_F5);
	MAP(KEY_F6);
	MAP(KEY_F7);
	MAP(KEY_F8);
	MAP(KEY_F9);
	MAP(KEY_F10);
	MAP(KEY_F11);
	MAP(KEY_F12);
	MAP(KEY_F13);
	MAP(KEY_F14);
	MAP(KEY_F15);
	MAP(KEY_F16);
	MAP(KEY_F17);
	MAP(KEY_F18);
	MAP(KEY_F19);
	MAP(KEY_F20);
	MAP(KEY_F21);
	MAP(KEY_F22);
	MAP(KEY_F23);
	MAP(KEY_F24);
	MAP(KEY_F25);
	MAP(KEY_KP_0);
	MAP(KEY_KP_1);
	MAP(KEY_KP_2);
	MAP(KEY_KP_3);
	MAP(KEY_KP_4);
	MAP(KEY_KP_5);
	MAP(KEY_KP_6);
	MAP(KEY_KP_7);
	MAP(KEY_KP_8);
	MAP(KEY_KP_9);
	MAP(KEY_KP_DECIMAL);
	MAP(KEY_KP_DIVIDE);
	MAP(KEY_KP_MULTIPLY);
	MAP(KEY_KP_SUBTRACT);
	MAP(KEY_KP_ADD);
	MAP(KEY_KP_ENTER);
	MAP(KEY_KP_EQUAL);
	MAP(KEY_LEFT_SHIFT);
	MAP(KEY_LEFT_CONTROL);
	MAP(KEY_LEFT_ALT);
	MAP(KEY_LEFT_SUPER);
	MAP(KEY_RIGHT_SHIFT);
	MAP(KEY_RIGHT_CONTROL);
	MAP(KEY_RIGHT_ALT);
	MAP(KEY_RIGHT_SUPER);
	MAP(KEY_MENU);
}

}
