name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Dependencies
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git build-essential cmake libglew-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl-dev gcc-10 g++-10
      - name: Use gcc-10
        run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10

      # Build project using CMake
      - name: Prepare build
        run: cmake .
      - name: Build project
        run: cmake --build .

      # Upload build artifacts
      - name: 'Upload a Build Artifact: sandbox'
        uses: actions/upload-artifact@v2
        with:
          name: sandbox
          path: ./sandbox/sandbox
      - name: 'Upload Build Artifact: libzoe.a'
        uses: actions/upload-artifact@v2
        with:
          name: libzoe.a
          path: ./zoe/libzoe.a

  docs:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Dependencies (copied from job 'build')
      - name: Install dependencies
        run: sudo apt-get install -y git doxygen graphviz build-essential cmake libglew-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl-dev gcc-10 g++-10
      - name: Use gcc-10
        run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10

      # Prepare and generate documentation
      - name: Prepare and generate documentation
        run: |
          rm -rf ./docs/
          sed -i "s/zoe-curr-commit-hash/Documentation revision \#$GITHUB_RUN_NUMBER/g" ./.doxyfile
          cmake .
          cmake --build . --target doc_doxygen

      # Upload ./docs/
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./docs/

      # Move generated files to branch 'docs'
      - name: Prepare commit to target branch
        run: |
          mv ./docs/ /tmp/zoe-docs/
          rm -rf *
      - uses: actions/checkout@v2
        with:
          ref: docs
      - name: Replace existing docs with the new ones
        run: |
          rm -rf ./docs/
          mv /tmp/zoe-docs/ ./docs/

      # Commit ./docs/
      - name: Commit update documentation
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add ./docs/
          git commit -am "Automatically updated documentation"
          git push
