name: Build (with CMake)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Dependencies
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y git build-essential cmake libglew-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl-dev
      - name: Use gcc-9
        run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9

      # Build project using CMake
      - name: Prepare build
        run: cmake .
      - name: Build project
        run: cmake --build .

      # Upload build artifacts
      - name: 'Upload a Build Artifact: sandbox'
        uses: actions/upload-artifact@v2
        with:
          name: sandbox
          path: ./sandbox/sandbox
      - name: 'Upload Build Artifact: libzoe.a'
        uses: actions/upload-artifact@v2
        with:
          name: libzoe.a
          path: ./zoe/libzoe.a

  docs:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Dependencies (copied from job 'build')
      - name: Install dependencies
        run: sudo apt install -y git doxygen graphviz build-essential cmake libglew-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl-dev
      - name: Use gcc-9
        run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9

      # Prepare CMake and Doxygen
      - name: Prepare build
        run: cmake .
      - name: Prepare doxygen
        run: rm -Rf ./docs/ && sed -i "s/zoe-curr-commit-hash/Documentation revision \#$GITHUB_RUN_NUMBER/g" ./.doxyfile

      # Run 'doc_doxygen' target
      - name: Generate docs
        run: cmake --build . --target doc_doxygen

      # Commit ./docs/
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: ./docs/*
          commit_message: Automatically update documentation
          commit_options: '--no-verify --signoff'
          commit_user_name: GitHub Actions
          commit_user_email: github-NudelErde-zoe@example.com

      # Upload ./docs/
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./docs/
